"use client";

import { useState } from "react";
import styles from "./ContactForm.module.css";

export function ContactForm({submitted=false}:{submitted?:boolean}) {
  const [status,setStatus]=useState<"idle"|"sending"|"success"|"error">(submitted?"success":"idle");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setStatus("sending");const form=event.currentTarget;try{const response=await fetch("https://formsubmit.co/ajax/saugatraina01@gmail.com",{method:"POST",headers:{Accept:"application/json"},body:new FormData(form)});const result=await response.json() as {success?:boolean|string};if(!response.ok||(result.success!==true&&result.success!=="true"))throw new Error();form.reset();setStatus("success")}catch{setStatus("error")}}
  if(status==="success")return <div className={styles.success}><h2>Thanks—your information has been received.</h2><p>Your consultation request was submitted successfully. I&apos;ll review the details you shared and follow up by email.</p><button type="button" onClick={()=>setStatus("idle")}>Send another inquiry</button></div>;
  return <form className={styles.form} onSubmit={submit}><input type="hidden" name="_subject" value="New marketing consultation request from Digital Saugat"/><input type="hidden" name="_template" value="table"/><input type="hidden" name="_url" value="https://portfolio.sikumna.com/contact"/><div className={styles.honeypot} aria-hidden="true"><label>Company website<input name="_honey" tabIndex={-1} autoComplete="off"/></label></div><div className={styles.row}><label>Full Name *<input name="name" autoComplete="name" required minLength={2}/></label><label>Business Name<input name="business" autoComplete="organization"/></label></div><div className={styles.row}><label>Email *<input name="email" type="email" autoComplete="email" required/></label><label>Phone / WhatsApp<input name="phone" type="tel" autoComplete="tel"/></label></div><label>Website<input name="website" type="url" placeholder="https://"/></label><label>What would you like help with?<select name="service" defaultValue="Not Sure Yet"><option>Meta Ads</option><option>Content Marketing</option><option>AI Automation</option><option>Website / Landing Page</option><option>Digital Marketing</option><option>Not Sure Yet</option></select></label><label>What&apos;s your biggest marketing challenge right now? *<textarea name="challenge" required minLength={10} rows={5}/></label><label>What would you like to achieve in the next 3–6 months?<textarea name="goal" rows={4}/></label><button className="btn btn-primary" type="submit" disabled={status==="sending"}>{status==="sending"?"Sending…":"Get My Free Marketing Plan"}</button>{status==="error"&&<p role="alert" className={styles.error}>Your message could not be sent. Please try again.</p>}<p className={styles.note}>I&apos;ll review your information before our consultation so we can make the conversation more useful.</p></form>;
}
